eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      override.system-properties: false # I do not want to override any properties inside the specific microservices configuration


management:
  tracing:
    sampling:
      probability: 1.0
