
server:
  port: 8070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: dekan
    password: s3cret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # because we want to rely on Flyway to create the schema for us
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments

