
server:
  port: 8050

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: dekan
    password: s3cret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # because we want to rely on Flyway to create the schema for us
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true # Whether we want to automatically call the baseline when migrating on empty schema
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  config:
    import: optional:configserver:http://localhost:8888