
spring:
  application:
    name: notification
  config:
    import: optional:configserver:http://localhost:8888

kafka:
  host: localhost:9092
  topics:
    order-confirmation:
      topic: order.order-confirmation.0
      consumerGroup: ${spring.application.name}-orderGroup
      replicationFactor: 1
      retentionInMs: 604800000
      autoOffsetReset: earliest
    payment-confirmation:
      topic: payment.payment-confirmation.0
      consumerGroup: ${spring.application.name}-paymentGroup
      replicationFactor: 1
      retentionInMs: 604800000
      autoOffsetReset: earliest



