spring:
  application:
    name: order
  config:
    import: optional:configserver:http://localhost:8888

kafka:
  host: localhost:9092
  topics:
    order-confirmation:
      topicName: ${spring.application.name}.order-confirmation.0
      partitionCount: 1
      replicationFactor: 1
      retentionInMs: 604800000