spring:
  application:
    name: payment
  config:
    import: optional:configserver:http://localhost:8888

kafka:
  host: localhost:9092
  topics:
    payment-confirmation:
      topicName: ${spring.application.name}.payment-confirmation.0
      partitionCount: 1
      replicationFactor: 1
      retentionInMs: 604800000